### PR TITLE
Update CurrencyInfo API test

### PR DESCRIPTION
**Pull request by archmagos**
Update the CurrencyInfoApiTest providing a Sender ID to satisfy a new
parameter recently added to the Java SDK. Fixes an issue preventing the
SDK from being built in Travis.

### CODE REVIEW

**Comment by sztupy** [comment]
So this is a breaking change. Adding a new optional parameter should never cause our existing SDKs to break. This is unfortunatley something we envisioned @CallumD 

This is not a huge problem at this point - as we don't have customers using the Java SDK, but this is going to be problematic in the future. Either we need to look at the codegenerator, or add a backward-compatibility layer in the future, e.g. something as simple as

```
class CurrencyInfoApi {
   Result infoCurrenciesIn() {
     return infoCurrenciesIn(null);
   }
}
```

but once we start adding things like this it'll become something to maintain

**Comment by CallumD** [comment]
We have a few changes that are coming up as well so this is going to be something that bites us in the near future. Can we create an investigation card to see how best to deal with this?

**Comment by sztupy** [comment]
Done: https://btcafrica.atlassian.net/browse/BTA-2041

**Comment by archmagos** [comment]
Thanks both. Closing this for now.

**Comment by sztupy** [comment]
This is fine for now

**Pull request merged**
